/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 29/06/2022 17:06:10
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLCLKFreq_Value                     50000000
#define MX_SYSCLKFreq_VALUE                     50000000
#define MX_HCLKFreq_Value                       50000000
#define MX_FCLKCortexFreq_Value                 50000000
#define MX_CortexFreq_Value                     50000000
#define MX_AHBFreq_Value                        50000000
#define MX_APB1Freq_Value                       25000000
#define MX_APB2Freq_Value                       50000000
#define MX_APB1TimFreq_Value                    50000000
#define MX_APB2TimFreq_Value                    50000000
#define MX_48MHZClocksFreq_Value                25000000
#define MX_EthernetFreq_Value                   50000000
#define MX_LCDTFTFreq_Value                     24500000
#define MX_I2SClocksFreq_Value                  192000000
#define MX_SAI_AClocksFreq_Value                24500000
#define MX_SAI_BClocksFreq_Value                24500000
#define MX_RTCFreq_Value                        32000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    50000000

/*-------------------------------- FMC        --------------------------------*/

#define MX_FMC                                  1

/* GPIO Configuration */

/* Pin PD15 */
#define MX_FMC_D1_Pin                           PD15
#define MX_FMC_D1_GPIOx                         GPIOD
#define MX_FMC_D1_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D1_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D1_GPIO_Pin                      GPIO_PIN_15
#define MX_FMC_D1_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D1_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PD7 */
#define MX_FMC_NCE2_Pin                         PD7
#define MX_FMC_NCE2_GPIOx                       GPIOD
#define MX_FMC_NCE2_GPIO_PuPd                   GPIO_NOPULL
#define MX_FMC_NCE2_GPIO_Speed_High_Default     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_NCE2_GPIO_Pin                    GPIO_PIN_7
#define MX_FMC_NCE2_GPIO_AF                     GPIO_AF12_FMC
#define MX_FMC_NCE2_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PD0 */
#define MX_FMC_D2_Pin                           PD0
#define MX_FMC_D2_GPIOx                         GPIOD
#define MX_FMC_D2_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D2_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D2_GPIO_Pin                      GPIO_PIN_0
#define MX_FMC_D2_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D2_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PD12 */
#define MX_FMC_ALE_Pin                          PD12
#define MX_FMC_ALE_GPIOx                        GPIOD
#define MX_FMC_ALE_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_ALE_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_ALE_GPIO_Pin                     GPIO_PIN_12
#define MX_FMC_ALE_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_ALE_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PD1 */
#define MX_FMC_D3_Pin                           PD1
#define MX_FMC_D3_GPIOx                         GPIOD
#define MX_FMC_D3_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D3_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D3_GPIO_Pin                      GPIO_PIN_1
#define MX_FMC_D3_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D3_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PD6 */
#define MX_FMC_NWAIT_Pin                        PD6
#define MX_FMC_NWAIT_GPIOx                      GPIOD
#define MX_FMC_NWAIT_GPIO_PuPd                  GPIO_NOPULL
#define MX_FMC_NWAIT_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_NWAIT_GPIO_Pin                   GPIO_PIN_6
#define MX_FMC_NWAIT_GPIO_AF                    GPIO_AF12_FMC
#define MX_FMC_NWAIT_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PE7 */
#define MX_FMC_D4_Pin                           PE7
#define MX_FMC_D4_GPIOx                         GPIOE
#define MX_FMC_D4_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D4_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D4_GPIO_Pin                      GPIO_PIN_7
#define MX_FMC_D4_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D4_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PE8 */
#define MX_FMC_D5_Pin                           PE8
#define MX_FMC_D5_GPIOx                         GPIOE
#define MX_FMC_D5_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D5_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D5_GPIO_Pin                      GPIO_PIN_8
#define MX_FMC_D5_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D5_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PE9 */
#define MX_FMC_D6_Pin                           PE9
#define MX_FMC_D6_GPIOx                         GPIOE
#define MX_FMC_D6_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D6_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D6_GPIO_Pin                      GPIO_PIN_9
#define MX_FMC_D6_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D6_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PE10 */
#define MX_FMC_D7_Pin                           PE10
#define MX_FMC_D7_GPIOx                         GPIOE
#define MX_FMC_D7_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D7_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D7_GPIO_Pin                      GPIO_PIN_10
#define MX_FMC_D7_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D7_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PD11 */
#define MX_FMC_CLE_Pin                          PD11
#define MX_FMC_CLE_GPIOx                        GPIOD
#define MX_FMC_CLE_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_CLE_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_CLE_GPIO_Pin                     GPIO_PIN_11
#define MX_FMC_CLE_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_CLE_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PD5 */
#define MX_FMC_NWE_Pin                          PD5
#define MX_FMC_NWE_GPIOx                        GPIOD
#define MX_FMC_NWE_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_NWE_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_NWE_GPIO_Pin                     GPIO_PIN_5
#define MX_FMC_NWE_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_NWE_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PD4 */
#define MX_FMC_NOE_Pin                          PD4
#define MX_FMC_NOE_GPIOx                        GPIOD
#define MX_FMC_NOE_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_NOE_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_NOE_GPIO_Pin                     GPIO_PIN_4
#define MX_FMC_NOE_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_NOE_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PD14 */
#define MX_FMC_D0_Pin                           PD14
#define MX_FMC_D0_GPIOx                         GPIOD
#define MX_FMC_D0_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_D0_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D0_GPIO_Pin                      GPIO_PIN_14
#define MX_FMC_D0_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_D0_GPIO_Mode                     GPIO_MODE_AF_PP

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 */
#define MX_SYS_JTMS_SWDIO_Pin                   PA13

/* Pin PA14 */
#define MX_SYS_JTCK_SWCLK_Pin                   PA14

/* Pin PB3 */
#define MX_SYS_JTDO_SWO_Pin                     PB3

/*-------------------------------- TIM14      --------------------------------*/

#define MX_TIM14                                1

/* GPIO Configuration */

/*-------------------------------- USART3     --------------------------------*/

#define MX_USART3                               1

#define MX_USART3_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PC10 */
#define MX_USART3_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART3_TX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART3_TX_Pin                        PC10
#define MX_USART3_TX_GPIOx                      GPIOC
#define MX_USART3_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART3_TX_GPIO_Pin                   GPIO_PIN_10
#define MX_USART3_TX_GPIO_AF                    GPIO_AF7_USART3

/* Pin PC11 */
#define MX_USART3_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART3_RX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART3_RX_Pin                        PC11
#define MX_USART3_RX_GPIOx                      GPIOC
#define MX_USART3_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART3_RX_GPIO_Pin                   GPIO_PIN_11
#define MX_USART3_RX_GPIO_AF                    GPIO_AF7_USART3

/* NVIC Configuration */

/* NVIC USART3_IRQn */
#define MX_USART3_IRQn_interruptPremptionPriority 0
#define MX_USART3_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_4
#define MX_USART3_IRQn_Subriority               0

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

#endif  /* __MX_DEVICE_H */

